import "./globals.css";
import Header from './components/header/Header'
import Footer from './components/footer/Footer'
import React from 'react'
import {mainFont, titleFont} from './fonts'
import {ToastContainer} from "react-toastify"
import 'react-toastify/dist/ReactToastify.css'
import WaWidget from "@/app/components/ui/WAwidget/WaWidget";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

// <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
export default function RootLayout({children}) {
    return (
        <html lang="ru">
        <body className={`${mainFont.variable} ${titleFont.variable}`}>
        <Header/>
        {children}
        <Footer/>
        {/*<ModalCB />*/}
        <ToastContainer/>
        <WaWidget/>
        </body>
        </html>
    );
}
