import "./globals.css";
import Header from './components/header/Header'
import Footer from './components/footer/Footer'
import React from 'react'
import {mainFont, titleFont} from './fonts'
import ModalCB from './components/modal/Modal'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className={`${mainFont.variable} ${titleFont.variable}`}>
      <Header />
      {children}
      <Footer />
      {/*<ModalCB />*/}
      </body>
    </html>
  );
}
